import { cp,mkdir,rm,writeFile } from 'node:fs/promises';
import path from 'node:path';
import { root,dataDir } from '../src/collect.mjs';
const dist=path.join(root,'dist');
await rm(dist,{recursive:true,force:true});await mkdir(path.join(dist,'data'),{recursive:true});
await cp(path.join(root,'public'),dist,{recursive:true});
for(const file of ['latest.json','historical.json','catalog.json','history'])await cp(path.join(dataDir,file),path.join(dist,'data',file),{recursive:true});
await writeFile(path.join(dist,'runtime.json'),JSON.stringify({mode:process.env.COLLECTION_MODE==='local'?'pages-local':'github',intervalMinutes:10}));
await writeFile(path.join(dist,'.nojekyll'),'');
console.log('정적 사이트 생성 완료: dist/');
