export const YEAR = 2027;
export const schools = [
  {id:'kyonggi',name:'경기대학교',shortName:'경기대',color:'#7197e0',provider:'uway',url:'https://ratio.uwayapply.com/Sl5KJXJyV2FiOUpmJSY6Jko3ZlRm',track:'논술(논술우수자전형)',cutoff:'12:00',close:'17:00',resultsUrl:'https://enter.kyonggi.ac.kr/cms/FR_CON/index.do?MENU_ID=130'},
  {id:'suwon',name:'수원대학교',shortName:'수원대',color:'#b09ae2',provider:'jinhak',url:'https://addon.jinhakapply.com/RatioV1/RatioH/Ratio10970461.html',track:'교과논술전형',cutoff:'12:00',close:'18:00',resultsUrl:'https://ipsi.suwon.ac.kr/board/susi_result'},
  {id:'koreatech',name:'한국기술교육대학교',shortName:'한국기술교육대',color:'#e1a068',provider:'uway',url:'https://ratio.uwayapply.com/Sl5KfExgMDhgfWE5SmYlJjomSjdmVGY=',track:'논술전형',cutoff:'18:00',close:'19:00',resultsUrl:'https://www.koreatech.ac.kr/menu.es?mid=a40102010100'},
  {id:'tukorea',name:'한국공학대학교',shortName:'한국공학대',color:'#6eb6b2',provider:'jinhak',url:'https://addon.jinhakapply.com/RatioV1/RatioH/Ratio30170741.html',track:'논술(논술우수자)',cutoff:'12:00',close:'18:00',resultsUrl:'https://iphak.tukorea.ac.kr/susi/result.htm'},
  {id:'gachon',name:'가천대학교',shortName:'가천대',color:'#e58d94',provider:'jinhak',url:'https://addon.jinhakapply.com/RatioV1/RatioH/Ratio10190711.html',track:'논술 전형',cutoff:'12:00',close:'18:00',resultsUrl:'https://admission.gachon.ac.kr/admission/html/rolling/result.asp'},
  {id:'sahmyook',name:'삼육대학교',shortName:'삼육대',color:'#8cae77',provider:'jinhak',url:'https://addon.jinhakapply.com/RatioV1/RatioH/Ratio10760741.html',track:'논술우수자전형',cutoff:'15:00',close:'18:00',resultsUrl:'https://ipsi.syu.ac.kr/2016_syu/pages/index.asp?p=10&b=B_1_7&cate=%BC%F6%BD%C3'},
  {id:'kangnam',name:'강남대학교',shortName:'강남대',color:'#c68c65',provider:'uway',url:'https://ratio.uwayapply.com/Sl5KTThXclc4OUpmJSY6Jko3ZlRm',track:'[정원내]논술위주(논술전형)',cutoff:'13:00',close:'18:00',resultsUrl:'https://admission.kangnam.ac.kr/iphak/stats.htm'},
  {id:'caudavinci',name:'중앙대학교 다빈치캠퍼스',sourceName:'중앙대학교',shortName:'중앙대 다빈치',campusFilter:'다빈치',color:'#677dbc',provider:'uway',url:'https://ratio.uwayapply.com/Sl5KOjhMSmYlJjomSjdmVGY=',track:'논술(일반형)',cutoff:'14:00',close:'18:00',publicationSchedule:'매일 10:00·17:00 발표. 9월 11일은 10:00·14:00 발표.',resultsUrl:'https://admission.cau.ac.kr/submenu.do?menuurl=lktmA6TpgpjUpNE2tkO4bw%3d%3d&'},
  {id:'hanshin',name:'한신대학교',shortName:'한신대',color:'#b77f96',provider:'jinhak',url:'https://addon.jinhakapply.com/RatioV1/RatioH/Ratio11630451.html',track:'논술',cutoff:'12:00',close:'18:00',resultsUrl:'https://ent.hs.ac.kr/ipsi/pages/?p=43&b=b_1_8'},
  {id:'inha',name:'인하대학교',shortName:'인하대',color:'#659dc0',provider:'uway',url:'https://ratio.uwayapply.com/Sl5KOHxXJUpmJSY6Jko3ZlRm',track:'논술 논술우수자',cutoff:'12:00',close:'18:00',publicationSchedule:'매일 10:00·14:00·17:00 발표. 9월 11일은 10:00·12:00, 최종 결과는 19:00 이후 공지 예정.',resultsUrl:'https://admission.inha.ac.kr/'},
  {id:'yonseim',name:'연세대학교 미래캠퍼스',sourceName:'연세대학교(미래)',shortName:'연세대 미래',color:'#8676bd',provider:'uway',url:'https://ratio.uwayapply.com/Sl5KZiVgJldhYkpmJSY6Jko3ZlRm',track:'논술[논술우수자전형]',cutoff:'14:00',close:'17:00',publicationSchedule:'매일 1시간 단위 발표.',resultsUrl:'https://admission.yonsei.ac.kr/mirae/admission/html/rolling/competition.asp'},
  {id:'ajou',name:'아주대학교',shortName:'아주대',color:'#69a58c',provider:'jinhak',url:'https://addon.jinhakapply.com/RatioV1/RatioH/Ratio11040711.html',track:'논술우수자전형',cutoff:'17:00',close:'18:00',publicationSchedule:'매일 10:00·13:00·17:00 발표. 최종 결과는 9월 11일 19:00 입학처 공지 예정.',resultsUrl:'https://www.iajou.ac.kr/rate/?m_type=SUSI'},
  {id:'kau',name:'한국항공대학교',shortName:'한국항공대',color:'#bf9c55',provider:'jinhak',url:'https://addon.jinhakapply.com/RatioV1/RatioH/Ratio11540991.html',track:'논술우수자 전형',cutoff:'15:00',close:'18:00',resultsUrl:'https://ibhak.kau.ac.kr/admission/html/rolling/result.asp'},
  {id:'kusejong',name:'고려대학교 세종캠퍼스',sourceName:'고려대학교(세종)',shortName:'고려대 세종',color:'#9d5265',provider:'uway',url:'https://ratio.uwayapply.com/Sl5KcldhL2AmOzhgfWE5SmYlJjomSjdmVGY=',track:'논술(일반전형)',cutoff:'15:00',close:'18:00',publicationSchedule:'매일 1시간 단위 발표. 9월 11일 경쟁률 공개는 15:00까지, 최종 경쟁률은 18:00 이후 공지.',resultsUrl:'https://oku.korea.ac.kr/sejong/cms/FR_CON/index.do?MENU_ID=500'},
  {id:'hongiksejong',name:'홍익대학교 세종캠퍼스',sourceName:'홍익대학교',sourceService:'수시모집(세종캠퍼스)',shortName:'홍익대 세종',color:'#4e91a3',provider:'jinhak',url:'https://addon.jinhakapply.com/RatioV1/RatioH/Ratio11720892.html',track:'논술전형',cutoff:'16:00',close:'18:00',publicationSchedule:'9월 7일 10:00부터 3시간 단위 발표. 9월 11일 경쟁률 공개는 16:00까지, 최종 경쟁률은 접수 마감 후 공지.',resultsUrl:'https://www.hongik.ac.kr/kr/admission/entrance-point.do'}
].map(s=>({...s,year:YEAR,intervalMinutes:10,publicationSchedule:s.publicationSchedule||'10분 단위 발표.',cutoffAt:`2026-09-11T${s.cutoff}:00+09:00`,closeAt:`2026-09-11T${s.close}:00+09:00`}));
